// Code generated by "stringer -type Fellowship enums.go"; DO NOT EDIT.

package main

import "strconv"

const _Fellowship_name = "AAAlAnonAlateen"

var _Fellowship_index = [...]uint8{0, 2, 8, 15}

func (i Fellowship) String() string {
	i -= 1
	if i < 0 || i >= Fellowship(len(_Fellowship_index)-1) {
		return "Fellowship(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Fellowship_name[_Fellowship_index[i]:_Fellowship_index[i+1]]
}
