// Code generated by "stringer -type=Tshirt"; DO NOT EDIT.

package main

import "strconv"

const _Tshirt_name = "Yes_T_Shirt_PleaseNo_T_Shirt"

var _Tshirt_index = [...]uint8{0, 18, 28}

func (i Tshirt) String() string {
	i -= 1
	if i < 0 || i >= Tshirt(len(_Tshirt_index)-1) {
		return "Tshirt(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Tshirt_name[_Tshirt_index[i]:_Tshirt_index[i+1]]
}
