// Code generated by "stringer -type=Willing"; DO NOT EDIT.

package main

import "strconv"

const _Willing_name = "Yes_WillingNo"

var _Willing_index = [...]uint8{0, 11, 13}

func (i Willing) String() string {
	i -= 1
	if i < 0 || i >= Willing(len(_Willing_index)-1) {
		return "Willing(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Willing_name[_Willing_index[i]:_Willing_index[i+1]]
}
